language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=DigitalOcean
    - REQUIRE=""

  matrix:
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1

before_script:
    - git clone git://github.com/cakephp/cakephp.git --branch $CAKE_REF --depth 1 ../cakephp
    - cp -R ../cakephp-digitalocean ../cakephp/app/Plugin/DigitalOcean
    - echo "CakePlugin::loadAll();" >> ../cakephp/app/Config/bootstrap.php
  
notifications:
  email: false
